### ISSUE TITLE
Recommended Watchers

### ISSUE THREAD

**Issue by shashankpr** [etherlabsio/ai-engine#139]
## Context
For any given PIM, action marker or topic marker, if we let users in the channel know that this is something that you may be interested in or something that is related to you/your work, then it provides more visibility, context and faster method of skimming through relevant parts of a meeting.

## Algorithmic ideas
Finding and obtaining set of relevant users for a given text or segment can be done in various ways (ordered by quickness and ease of implementation. As we go lower the order, we obtain the best recommendation process)

1. **Keyphrases & Entity comparison**: 
In a given meeting, we persist the top-n keyphrases alongwith their feature vectors for every spoken segment. Using EtherGraph, these keyphrases can be mapped to the user who authored the segments. By stacking and aggregating keyphrase features we can form an embedding for the user. This user embedding can be used to check the similarity with other users, segments or marker texts.
This method uses aggregation of keyphrase features for comparison. This is simple yet not highly informative for longer run.

2. **User embedding comparison**:  
For a given user we have more information other than keyphrases, like spoken segments, markers created, marker description and/or slack text. We can create a richer user embedding space by taking each of these feature vectors and perform a complex aggregation method like matrix factorization or neural embedding aggreation.
References:
- https://arxiv.org/pdf/1706.01084.pdf
- https://www.ijcai.org/proceedings/2018/0219.pdf
- https://github.com/facebookresearch/StarSpace

3. **User relations**:
Once we have the signature or embedding for a user, we can use EtherGraph to find links between Users. Links can be in the form of common marker creation (assignee & assigned to), common set of keyphrases/entities/topics, users with most commonly referred mind and team information.
This way we can have a user embedding consisting of other linked user's embedding. This is particularly useful for users who have less information or have newly joined.

## Design Process
The steps are based on point 1 of the above algorithmic methods.

1. Receive an input in the form of `segmentId` or `markerId`
2. Query EtherGraph for the given input ID and get the feature vectors of the segment and the keyphrases. These form the `base_embedding`.
3. Query for all the users and the keyphrases associated with for a given channel. The query depth (traversals) could range from 4 - 10 recent meetings. 
4. Form simple user embeddings by aggregating their keyphrase embeddings.
5. Create a mapping of `userId -> feature vector` for comparison with `base_embedding`. 
6. Using similarity measures, get the top-n users that are closest to the `base_embedding`.

## Sample input & output
**Input**
```js
{
    "contextId":"6baa3490",
    "instanceId":"b5d4",
    "relativeTime": "2019-01-29T06:03:39.783385299Z",
    "segments": [
        {
            "id": "0f1aa05f2e944142a18974369bb9b789"
        }
    ]
}
```

**Output**
```js
{
    "contextId":"6baa3490",
    "instanceId":"b5d4",
    "relativeTime": "2019-01-29T06:03:39.783385299Z",
    "confidence": 0.88,
    "users": [
        {
            "userId": "abc",
        },
        {
            "userId": "xyz",
        }
    ],
    "commonKeyphrases": [
        "lambda functions, mind deployment, terraform changes, Action item detection
    ]
}
```
Confidence scores and `commonKeyphrases` are computed to provide explainability  for the recommended user (if needed) and for internal debugging purposes. 

## Tasks 
Most of the tasks leading to this feature are laid out in #130 and https://github.com/etherlabsio/api/issues/591 since we need a running instance of Dgraph with all the s2 or production graphs populated so as to obtain recommended users across the meetings.

- [x] Dgraph population from existing networkX dump - #112 
- [x] Basic EtherGraph service for continuous population of meetings and keyphrases - #137 , #144 
- [x] Set up Dgraph instance in staging2 for POC and testing
