### ISSUE TITLE
Populate and persist only summary-segments

### ISSUE THREAD

**Issue by shashankpr** [etherlabsio/ai-engine#163]
## Scenario
Earlier, for PIMs we used to get top-5 segments which pertained to 5 individual segments. Since, 5 segments were too less a number to have user info like keyphrases spoken, entities etc, we decided to populate attributes for every segment.
This gives us a high set of information but compromises with the quality of Ether Graph

## Current case
Since we have switched to grouped summaries, every summary topic has a rich set of information already. Just persisting them would maintain good quality of graph and also prevents data redundancy.

## Tasks
- [x] Populate only summary segments
- [x] Store the group information (group Id etc)
- [x] Since keyphrases for a group will be same for all the segments in a group, persist individual segment-level phrases (helpful for user attributes)
- [x] Redesign the ether-graph service to delete attributes of non-summary segments (attributes like phrases, entities etc.) at the end of the meeting.
