### ISSUE TITLE
Continuous graph population - Ether Graph tasks

### ISSUE THREAD

**Issue by shashankpr** [etherlabsio/ai-engine#172]
To track the tasks pending before continuous graph population can be enabled in production are listed below:
- [x] Standardize graph schema and connections through python structs
- [x] Add the following connections: 
- [x] User --> Entities, User --> User (groupedWith), User --> User (recommended/related), Entities --> Keyphrase (relatedTo)
- [x] Populate only summary phrases (#163)
- [x] Add logic to cleanup graph after `context.instance.ended` and remove non-highlight phrases.
- [x] Fix dateTime format issue in production data and set dateTime as index for sorting (#156)
- [ ] Add support for Facets (#182)
- [ ] Separate Dgraph client as a common pkg in `ai-engine` or `api`
